### ISSUE TITLE
Incorrect Calculation of Long and Latitude

### ISSUE THREAD

**Issue by almeidor** [MaJerle/GPS_NMEA_parser#10]
static gps_float_t parse_lat_long(gps_t* gh) in gps.c has an issue with the calculation of deg, where it is returning a float with a remainder (not an integer number as required). This affects the calculation of ll later on by adding this remainder. Should read deg = (int)(ll / FLT(100)); 
Made the change and tested with real location data and the longitude and latitude returned are now correct.

**Comment by MaJerle** [comment]
Can you propose pull request?
