### ISSUE TITLE
CRC calculation

### ISSUE THREAD

**Issue by gutcZHAW** [MaJerle/GPS_NMEA_parser#2]
Hi

First of all thank you for providing this source code!
It was easy to implement it in my project.
I just made a few changes to get all necessary informations (date, time, position) only from GPRMC messages.

But I'm a little bit confused about the CRC calculation. From my gps device (Tersus BX306) I receive messages like this:

``$GNRMC,074546.00,A,4729.8111766,N,00843.7848026,E,0.094, 0.0,160818,0.0,E,A*0A``

When I check the checksum with an online calculator like [this ](http://nmeachecksum.eqth.net/) one,
the checksum seems to be valid. But when I check this sentence with the crc calculator in your nmea parser, the checksum seems to be incorrect because the space sign is omited for the crc calculation.
Why is the space sign omited in this crc calculation? I can't find any definitions like this for the crc calculation.

Thanks for your info :)

**Comment by MaJerle** [comment]
Hm, this was a good catch. Not sure why receiver replies with space but it seems valid statement. Fixed.
