### ISSUE TITLE
Library not updated on Platform IO registry

### ISSUE THREAD

**Issue by glbsalazar** [MaJerle/GPS_NMEA_parser#30]
I was planning on using the library via Platform IO but noticed that the registry does not have the latest version (it only has 2.1.0)
It should be automatically updated but it seems it wasn't and version 2.2.0 was already published several weeks ago (it should only take a couple of days)

Could there be an issue with the library.json file or with the integration with PlatformIO registry?

**Comment by MaJerle** [comment]
I did/do not manually publish the library to the Platform.IO.

This may be the reason, except if it can be done automatically.

**Comment by glbsalazar** [comment]
Could you publish the new version to platformio?
I am not sure why the new version was not picked up automatically

**Comment by MaJerle** [comment]
I'm not able to login to pio right now.
https://github.com/platformio/platformio-core/issues/4793

**Comment by ivankravets** [comment]
Oh, we don't know how the libraries were published to the registry because the automatic mode was not enabled for them. 

@MaJerle , if you didn't publish libraries manually, it could be the migration issue (PIO's old registry to the new one).

Nevertheless, we have just manually enabled automatic updates for https://registry.platformio.org/libraries/majerle/LwGPS

Do you prefer manually publishing the new versions?

**Comment by MaJerle** [comment]
Correct, I haven't enabled anything automatically, but target is indeed to make it automatic (since the feature exists). Could you please share a link where I can see the way to auto publish? Target would be to get an event on publishing new tag (vX.Y,Z).

**Comment by ivankravets** [comment]
You don't need to do any steps. We already enabled the legacy crawler for this library. The crawler checks manifest 1 time per 24h. So, the crawler will automatically pull the new version when you update the `library.json` "version" field and make a new tag.

**Comment by glbsalazar** [comment]
Thanks @MaJerle and @ivankravets, I see that the library was updated in platformio.

**Comment by MaJerle** [comment]
Yes, lib is there now.

Thanks to all for reporting and help!
