### ISSUE TITLE
Header file not found when included via Platform IO

### ISSUE THREAD

**Issue by glbsalazar** [MaJerle/GPS_NMEA_parser#31]
While adding the library via PlatformIO with `lib_deps = majerle/LwGPS@^2.1.0`

The following error is produced during the build:
```
.pio\libdeps\swo_demo\LwGPS\lwgps\src\lwgps\lwgps.c:36:10: fatal error: lwgps/lwgps.h: No such file or directory
   36 | #include "lwgps/lwgps.h"
```

It seems that the header file cannot be found, neither to build the library nor to include it in the project.

**Comment by MaJerle** [comment]
Platformio builder (and compiler behind) should have "include folder" set to at least `lwgps/src/include`

If you have access to `library.json` before you build the project, you may try to modify it and add the `build` keyword with `includeDir` parameter:
https://docs.platformio.org/en/latest/manifests/library-json/index.html

If it works, I will update the project.

**Comment by glbsalazar** [comment]
Thanks for merging the proposed PR. Can a 2.2.1 be release that it is usable within PlatformIO without having to change the library.json file manually?
