### ISSUE TITLE
Header not found

### ISSUE THREAD

**Issue by alwinhb** [MaJerle/GPS_NMEA_parser#34]
@MaJerle Looks like header is present in the directory - Still the issue is there. Can you guide ?

root@db-ubuntu:/home/vboxuser/Downloads/lwgps-main/examples# make test
cc -o example.exe -Wall -DDEBUG=1 -I../lwgps/src/include -I./ ../lwgps/src/lwgps/lwgps.c example.c
In file included from ../lwgps/src/include/lwgps/lwgps.h:40,
                 from ../lwgps/src/lwgps/lwgps.c:36:
../lwgps/src/include/lwgps/lwgps_opt.h:42:10: fatal error: lwgps_opts.h: No such file or directory
   42 | #include "lwgps_opts.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
In file included from ../lwgps/src/include/lwgps/lwgps.h:40,
                 from example.c:7:
../lwgps/src/include/lwgps/lwgps_opt.h:42:10: fatal error: lwgps_opts.h: No such file or directory
   42 | #include "lwgps_opts.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:40: example.exe] Error 1

**Comment by MaJerle** [comment]
Your compiler does not have include paths set to the opts file.

**Comment by alwinhb** [comment]
@MaJerle I have added the opts in the current directories still I can see similar error message

**Comment by alwinhb** [comment]
@MaJerle Can you guide on its resolution?

**Comment by MaJerle** [comment]
As simple as it gets, your compiler does not see `lwgps_opts.h` file in your compilation path.

**Comment by alwinhb** [comment]
@MaJerle I did that, But still the same issue!

I have added this to my bash rc 

CPATH=/home/vboxuser/Downloads/lwgps-main/lwgps/src/include/lwgps/

**Comment by MaJerle** [comment]
https://docs.majerle.eu/projects/lwgps/en/latest/get-started/index.html#configuration-file

You need to create a file.

**Comment by alwinhb** [comment]
The issue was solved there is a type error in this file --> https://github.com/MaJerle/lwgps/blob/develop/lwgps/src/include/lwgps/lwgps_opt.h

Refer to line number 42, It's calling its own name in the header.

**Comment by MaJerle** [comment]
It does not, file is perfectly ok. File name you linked is `lwgps_opt.h`, while this file includes user's file `lwgps_opts.h`. Notice `s` at the end of user file.

https://github.com/MaJerle/lwgps/blob/cfdba723e020696f9af951a01be67e2bef8ae795/lwgps/src/include/lwgps/lwgps_opt.h#L41-L43
