### ISSUE TITLE
Knots Conversion

### ISSUE THREAD

**Issue by temporaryaccount** [MaJerle/GPS_NMEA_parser#5]
According to [this website](https://www.convertunits.com/from/knots/to/km/h) 1 knot is 1.852 km/h but this library is using 1.852 to convert knots to miles, and something else for km/h:

```C
    ...
    case gps_speed_kph:     return (gps_float_t)(sik * 0.5144L);
    case gps_speed_mps: return (gps_float_t)(sik * 1.852L);
    ...
```

**Comment by MaJerle** [comment]
Confirmed, fixed, thanks. Values are opposite here.
