### ISSUE TITLE
Floating Point Types

### ISSUE THREAD

**Issue by temporaryaccount** [MaJerle/GPS_NMEA_parser#6]
There are some issues that I can see coming from the fact that **GPS_NMEA_parser** is supporting two types of floating point numbers (float and double).

1.

When using doubles we might lose some precision because of this:

```C
    #define D2R(x)              (float)((x) * 0.01745329251994f)    /*!< Degrees to radians */
    #define R2D(x)              (float)((x) * 57.29577951308232f)   /*!< Radians to degrees */
    #define EARTH_RADIUS (6371.0f) /*!< Earth radius in units of kilometers */
```

For example, even if df, lae and las are all double in this line from `gps_distance_bearing` function, df will have float's precision:

df = D2R(lae - las);

I suggest to change the three lines above to this:

```C
    #define D2R(x)       ((gps_float_t)(x) * (gps_float_t)0.01745329251994)  /*!< Degrees to radians */
    #define R2D(x)       ((gps_float_t)(x) * (gps_float_t)57.29577951308232) /*!< Radians to degrees */
    #define EARTH_RADIUS ((gps_float_t)6371.0)                               /*!< Earth radius in units of kilometers */
```

2.

Not only here, but everywhere else we should replace the "f"-suffixed values to (gps_float_t)value.

3.

In `gps_to_speed` function we are for some reason using "L"-suffix values (long double!). Again I would suggest to change them to explicit type setting with (gps_float_t) and removing the suffix.

4.

`atan2`, `sin`, `cos`, `sqrt` and other functions from <math.h> used by this library are using double precision calculation even if our `gps_float_t` is set to `float`. For a small microcontroller device this gives a heavy penalty. We must use the "f"-suffixed functions when our `gps_float_t` is set to `float`: `atan2f`, `sinf`, `cosf`, `sqrtf`, etc..

Thank you.

**Comment by MaJerle** [comment]
Done.

**Comment by temporaryaccount** [comment]
That's incredible, thank you!

If it's not too much, can I suggest one more thing?

Current:

```C
static gps_float_t
parse_float_number(gps_t* gh, const char* t) {
    double res;

    if (t == NULL) {
        t = gh->p.term_str;
    }
    /* Strip leading spaces */
    while (t != NULL && *t == ' ') {
        t++;
    }
    res = strtod(t, NULL);                      /* Parse string to double */
    return FLT(res);                            /* Return casted value, based on float size */
}
```

Suggestion:

```C
static gps_float_t
parse_float_number(gps_t* gh, const char* t) {
    gps_float_t res;

    if (t == NULL) {
        t = gh->p.term_str;
    }
    /* Strip leading spaces */
    while (t != NULL && *t == ' ') {
        t++;
    }

#if GPS_CFG_DOUBLE
    res = strtod(t, NULL);                      /* Parse string to double */
#else /* GPS_CFG_DOUBLE */
    res = strtof(t, NULL);                      /* Parse string to double */
#endif /* GPS_CFG_DOUBLE */

    return FLT(res);                            /* Return casted value, based on float size */
}
```

**Comment by MaJerle** [comment]
Hmm, this I added and somehow reverted.
