### ISSUE TITLE
GPS geoid calculation

### ISSUE THREAD

**Issue by FreeVario** [MaJerle/GPS_NMEA_parser#7]
Hi there, 

Great parser, easy to use. I found problem with the altitude calculation. I seems that you have to subtract the geoid from the altitude. (https://eos-gnss.com/elevation-for-beginners/) In your code at line 191:   gh->p.data.gga.altitude += parse_double_number(gh, NULL);
Should it not be   gh->p.data.gga.altitude -= parse_double_number(gh, NULL); ?
Thanks
Marco

**Comment by MaJerle** [comment]
@FreeVario thanks for feedback. I believe code is right, according to answer here and explanation. https://gis.stackexchange.com/questions/174046/relation-between-geoidal-separation-and-antenna-altitude-in-gga-sentence

**Comment by FreeVario** [comment]
Yes, that's what so confusing. There are two formulas h=H+N and H = h – N. I think we should calculate H, and not h. The problem I'm having is that I'm feeding the same NMEA data to XCtrack and it is showing the correct altitude while the NMEA parser lib shows 50 meters higher.

**Comment by MaJerle** [comment]
Can you post here full NMEA statements to see? Thanks.

**Comment by FreeVario** [comment]
XCtrack is reporting altitude between -4 and -12 meters. That close enough to be accurate. I think it XCTrack is ignoring the geoid calculation. Looking at the geoid value (47.1) it does not matter which formula I use, it will never be correct. I'm wondering if the GPS is giving the wrong geoid values. Might be better if I disable the geoid calculation in the library. 

[Bluetooth Terminal HC-05-2.txt](https://github.com/MaJerle/GPS_NMEA_parser/files/3081751/Bluetooth.Terminal.HC-05-2.txt)
[Bluetooth Terminal HC-05.txt](https://github.com/MaJerle/GPS_NMEA_parser/files/3081752/Bluetooth.Terminal.HC-05.txt)

**Comment by FreeVario** [comment]
This also uses H = h – N.
[https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html](url)
Your Input Coordinates and GPS Height:
Latitude: 52.0897222222222° N = 52° 5' 23" N
Longitude: 4.53527777777778° E = 4° 32' 7" E
GPS ellipsoidal height: -4 (meters)
Geoid height: 43.328 (meters)
Orthometric height (height above EGM96 geoid which approximates mean sea level): -47.328 (meters)
(Note: orthometric height = GPS ellipsoidal height - geoid height)

I think that XCTrack is also in the wrong here by not calculating the amsl.

**Comment by MaJerle** [comment]
I see your point. If height is negative by received, we need to subtract it as absolute height is then higher than from GPS. So `-` is better then.

**Comment by FreeVario** [comment]
Yes, but, also, the altitude value of GGA sentence, already is based on MSL (mean sea level), for my use (paragliding) the conversion must therefore not be done (we use amsl standard for altitude), which explains the conflict with XCTrack. I'm going to remove the conversion in my code. Maybe it's easier if you have the altitude and geoid as seperate values, those who need to do a conversion can then do it in their own code.
Anyway thanks for your help! I'm on the right track again.

**Comment by MaJerle** [comment]
Done.
